import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NavBar";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body>
        <Providers>
          <NavBar />
          <main className="p-5">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
